sudo: false
language: ruby
rvm:
  - 2.3.3

cache: bundler
bundler_args: --without production

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - source .env.test
  - psql -c "create database ${HTML_PARSER_DB_NAME:-html_parser_test};" -U postgres
